config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :users
  resources :suppliers
  resources :brands
  resources :products
  resources :purchase_orders
  resources :sales_orders
  resources :inventories

  get "browserconfig", to: "home#browserconfig", constraints: lambda { |req| req.format == :xml }, as: "browserconfig"
  get "site", to: "home#site", constraints: lambda { |req| req.format == :webmanifest }, as: "webmanifest"

  # error pages
  %w(400 403 404 405 406 409 422 500 501).each do |code|
    get code, to: "exceptions#index", defaults: { code: }
  end

  devise_for :users,
    path: "",
    controllers: {
      sessions: "users/sessions",
      passwords: "users/passwords"
    },
    path_names: {
      sign_in: "/login",
      password: "/forgot",
      sign_out: "/logout"
    }
end

app/models/inventory.rb
# frozen_string_literal: true

class Inventory
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :product

  field :quantity, type: Integer
  field :selling_price, type: Float
  field :inventory_type, type: String

  validates :quantity, comparison: { greater_than_or_equal_to: 0 }
end

app/controllers/inventories_controller.rb
# frozen_string_literal: true
# typed: true

class InventoriesController < ApplicationController
  before_action :set_inventory, only: [ :show, :edit, :update, :destroy ]
  before_action :set_lookups, only: [ :new, :edit ]

  respond_to :html, :json

  def index
    respond_to do |format|
      format.html
      format.json do
        @inventories = Inventory.collection.aggregate([
          {
            "$lookup": {
              "from": "products",
              "localField": "product_id",
              "foreignField": "_id",
              "as": "product"
            }
          },
          {
            "$unwind": "$product",
          },

          {
            "$lookup": {
              "from": "brands",
              "localField": "product.brand_id",
              "foreignField": "_id",
              "as": "brand"
            }
          },
          {
            "$unwind": "$brand"
          },
          {
            "$sort": {
              "product.name": 1,
              "brand.name": 1,
              "name": 1
            }
          },
          {
            "$addFields": {
              "product_name": "$product.name",
              "brand_name": "$brand.name"
            }
          },
          {
            "$replaceRoot": {
              "newRoot": "$$ROOT"
            }
          }
        ]).map do |doc|
          doc["inventory_type"] = doc["inventory_type"].titleize
          Inventory.instantiate(doc)
        end
        respond_with(@inventories)
      end
    end
  end

  def show
    respond_with(@inventory)
  end

  def new
    @inventory = Inventory.new
    respond_with(@inventory)
  end

  def edit
    # edit
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.save
    respond_with(@inventory)
  end

  def update
    @inventory.update(inventory_params)
    respond_with(@inventory)
  end

  def destroy
    @inventory.destroy!
    respond_with(@inventory)
  end

  private
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    def set_lookups
      @products = Product.all.map { |product| [ product.name, product.id ] }
      @inventory_types = [["Hardware", "hardware"], ["Motor Parts", "motor_parts"]]
    end

    def inventory_params
      params.expect(
        inventory: [
          :brand_id,
          :product_id,
          :quantity,
          :selling_price
        ]
      )
    end
end

app/helpers/inventories_helper.rb
# frozen_string_literal: true

module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with model: inventory, class: "flex flex-col gap-2", id: "inventory-form" do |form| %>
  <% if inventory.errors.any? %>
    <div class="text-red-600">
      <h2><%= pluralize(inventory.errors.count, "error") %>
        prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label class="form-control w-full max-w-xs">
    <div class="label">
      <span class="label-text">Product</span>
    </div>
    <%= form.select :product_id, @products, { include_blank: "Select Product" }, { class: "select select-bordered w-full max-w-xs", disabled: (action_name == "edit") } %>
  </label>

  <label class="form-control w-full max-w-xs">
    <div class="label">
      <span class="label-text">Inventory Type</span>
    </div>
    <%= form.select :inventory_type, @inventory_types, { include_blank: "Select Supplier" }, { class: "select select-bordered w-full max-w-xs" } %>
  </label>

  <label class="form-control w-full max-w-xs">
    <div class="label">
      <span class="label-text">Quantity</span>
    </div>
    <%= form.number_field :quantity, min: 1, class: "input input-bordered w-full max-w-xs" %>
  </label>

  <label class="form-control w-full max-w-xs">
    <div class="label">
      <span class="label-text">Selling Price</span>
    </div>
    <div class="w-full flex flex-row gap-2 items-center">
      <span class="text-2xl">₱</span>
      <%= form.number_field :selling_price, min: 0.00, class: "input input-bordered w-full max-w-xs" %>
    </div>
  </label>
<% end %>

<div class="card-actions mt-4">
  <input type="submit" value="Save" form="inventory-form" class="btn btn-primary">
  <%= link_to "Cancel", inventories_path, class: "btn btn-neutral" %>
</div>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>" class="flex flex-col gap-2">
  <div>
    <strong>Brand Name:</strong>
    <%= inventory.product.brand.name %>
  </div>

  <div>
    <strong>Product Name:</strong>
    <%= inventory.product.name %>
  </div>

  <div>
    <strong>Quantity:</strong>
    <%= inventory.quantity %>
  </div>

  <div>
    <strong>Selling Price:</strong>
    <%= number_to_currency(inventory.selling_price, unit: "₱") %>
  </div>
</div>

app/views/inventories/edit.html.erb
<% content_for :title, "Update Inventory" %>

<div class="card bg-base-200 shadow-xl">
  <div class="card-body">
    <div class="card-title">
      <h1 class="text-4xl font-bold">Update Inventory</h1>
    </div>

    <%= render "form", inventory: @inventory %>
  </div>
</div>

app/views/inventories/index.html.erb
<% content_for :title, "Inventories" %>

<p class="text-green-600"><%= notice %></p>

<h1 class="text-4xl font-bold">Inventories</h1>

<div class="flex flex-col gap-2" x-data="inventories">
  <div class="w-full flex flex-row justify-between gap-2">
    <label class="input input-bordered flex items-center gap-2">
      <input @input.debounce="search($event.target.value)" type="text" class="grow" placeholder="Search"/>
      <iconify-icon icon="mdi:magnify" width="20"></iconify-icon>
    </label>
    <%= link_to "New inventory", new_inventory_path, class: "btn btn-primary" %>
  </div>

  <div class="overflow-x-auto rounded-box border-2 border-base-content/5 bg-base-100">
    <table class="table table-zebra table-lg" id="inventories">
      <thead>
        <tr class="bg-base-300 text-base-content">
          <template x-for="column in columns" :key="column.name">
            <th @click="sort(column.name)" class="cursor-pointer">
              <div class="flex flex-row items-center gap-1">
                <span x-text="column.label"></span>
                <template x-if="sortCol === column.name && !sortAsc">
                  <iconify-icon width="16" icon="mdi:arrow-down" class="text-white">
                  </iconify-icon>
                </template>
                <template x-if="sortCol === column.name && sortAsc">
                  <iconify-icon width="16" icon="mdi:arrow-up" class="text-white">
                  </iconify-icon>
                </template>
              </div>
            </th>
          </template>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <template x-if="isLoading">
          <tr class="hover">
            <td colspan="8" class="text-center">
              <i>Loading...</i>
            </td>
          </tr>
        </template>
        <template x-if="!data.length && !isLoading">
          <tr class="hover">
            <td colspan="8" class="text-center">
              <i>No data found.</i>
            </td>
          </tr>
        </template>
        <template x-for="inventory in data" :key="inventory._id">
          <tr class="hover">
            <td x-text="inventory.inventory_type"></td>
            <td x-text="inventory.brand_name"></td>
            <td x-text="inventory.product_name"></td>
            <td x-text="inventory.quantity"></td>
            <td x-text="NumberToCurrency.format(inventory.price)"></td>
            <td>
              <a :href="`/inventories/${inventory._id}`" class="btn btn-primary">View</a>
            </td>
          </tr>
        </template>
      </tbody>
    </table>
  </div>
</div>

<% content_for :page_script do %>
  <script>
    document.addEventListener("alpine:init", () => {
       Alpine.data('inventories', () => ({
        originalData: [],
        data: [],
        sortCol: null,
        sortAsc: null,
        isLoading: true,
        columns: [
          { name: "inventory_type", label: "Type" },
          { name: "brand_name", label: "Brand Name" },
          { name: "product_name", label: "Product Name" },
          { name: "quantity", label: "Quantity" },
          { name: "selling_price", label: "Selling Price" },
        ],
        async init() {
          let resp = await fetch('/inventories.json');
          this.originalData = await resp.json();
          this.data = [...this.originalData];
          this.isLoading = false;
        },
        sort (col) {
          this.sortCol = col;
          if (this.sortCol === col && this.sortAsc === false) {
            this.sortCol = null;
            this.sortAsc = null;
            this.data = [...this.originalData];
            return;
          }

          if (this.sortCol === col) this.sortAsc = this.sortAsc === null ? true : !this.sortAsc;
          this.data.sort((a, b) => {
            if (a[this.sortCol] < b[this.sortCol]) return this.sortAsc ? 1 : -1;
            if (a[this.sortCol] > b[this.sortCol]) return this.sortAsc ? -1 : 1;
            return 0;
          });
        },
        search (query) {
          if (!query.trim()) {
            this.data = [...this.originalData];
            return;
          }

          query = query.toLowerCase();
          this.data = [...this.originalData].filter(p => {
            return Object.values(p).some(v => String(v).toLowerCase().includes(query));
          });
        }
      }))
    });
  </script>
<% end %>

app/views/inventories/new.html.erb
<% content_for :title, "Create Inventory" %>

<div class="card bg-base-200 shadow-xl">
  <div class="card-body">
    <div class="card-title">
      <h1 class="text-4xl font-bold">Create inventory</h1>
    </div>

    <%= render "form", inventory: @inventory %>
  </div>
</div>

app/views/inventories/show.html.erb
<p class="text-green-600"><%= notice %></p>

<div class="card bg-base-200 shadow-xl">
  <div class="card-body">
    <div class="card-title">
      <h1 class="text-4xl font-bold">Inventory Details</h1>
    </div>

    <%= render @inventory %>

    <div class="card-actions mt-4">
      <%= link_to "Update inventory", edit_inventory_path(@inventory), class: "btn btn-primary" %>
      <%= link_to "Back", inventories_path, class: "btn btn-neutral" %>
    </div>
  </div>
</div>