config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :users
  resources :suppliers
  resources :brands
  resources :products
  resources :purchase_orders
  resources :sales_orders
  resources :inventories

  get "browserconfig", to: "home#browserconfig", constraints: lambda { |req| req.format == :xml }, as: "browserconfig"
  get "site", to: "home#site", constraints: lambda { |req| req.format == :webmanifest }, as: "webmanifest"

  # error pages
  %w(400 403 404 405 406 409 422 500 501).each do |code|
    get code, to: "exceptions#index", defaults: { code: }
  end

  devise_for :users,
    path: "",
    controllers: {
      sessions: "users/sessions",
      passwords: "users/passwords"
    },
    path_names: {
      sign_in: "/login",
      password: "/forgot",
      sign_out: "/logout"
    }
end

app/models/brand.rb
# frozen_string_literal: true

class Brand
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :products, dependent: :destroy

  field :name, type: String

  validates :name, presence: true, uniqueness: true
end

app/controllers/brands_controller.rb
# frozen_string_literal: true
# typed: true

class BrandsController < ApplicationController
  before_action :set_brand, only: [ :show, :edit, :update, :destroy ]

  respond_to :html, :json

  def index
    respond_to do |format|
      format.html
      format.json do
        @brands = Brand.collection.aggregate([
          {
            "$sort": {
              "name": 1
            }
          },
        ]).map do |doc|
          Brand.instantiate(doc)
        end
        respond_with(@brands)
      end
    end
  end

  def show
    respond_with(@brand)
  end

  def new
    @brand = Brand.new
    respond_with(@brand)
  end

  def edit
    # edit
  end

  def create
    @brand = Brand.new(brand_params)
    @brand.save
    respond_with(@brand)
  end

  def update
    @brand.update(brand_params)
    respond_with(@brand)
  end

  def destroy
    @brand.destroy!
    respond_with(@brand)
  end

  private
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.expect(brand: [:name])
    end
end

app/helpers/brands_helper.rb
# frozen_string_literal: true

module BrandsHelper
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id brand %>" class="flex flex-col gap-2">
  <div>
    <strong>Name:</strong>
    <%= brand.name %>
  </div>
</div>

app/views/brands/_form.html.erb
<%= form_with model: brand, class: "flex flex-col gap-2", id: "brand-form" do |form| %>
  <% if brand.errors.any? %>
    <div class="text-red-600">
      <h2><%= pluralize(brand.errors.count, "error") %>
        prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label class="form-control w-full max-w-xs">
    <div class="label">
      <span class="label-text">Name</span>
    </div>
    <%= form.text_field :name, class: "input input-bordered w-full max-w-xs" %>
  </label>
<% end %>

<div class="card-actions mt-4">
  <input type="submit" value="Save" form="brand-form" class="btn btn-primary">
  <%= link_to "Cancel", brands_path, class: "btn btn-neutral" %>
</div>

app/views/brands/edit.html.erb
<% content_for :title, "Update Brand" %>

<div class="card bg-base-200 shadow-xl">
  <div class="card-body">
    <div class="card-title">
      <h1 class="text-4xl font-bold">Update Brand</h1>
    </div>

    <%= render "form", brand: @brand %>
  </div>
</div>

app/views/brands/index.html.erb
<% content_for :title, "Brands" %>

<p class="text-green-600"><%= notice %></p>

<h1 class="text-4xl font-bold">Brands</h1>

<div class="flex flex-col gap-2" x-data="brands">
  <div class="w-full flex flex-row justify-between gap-2">
    <label class="input input-bordered flex items-center gap-2">
      <input @input.debounce="search($event.target.value)" type="text" class="grow" placeholder="Search"/>
      <iconify-icon icon="mdi:magnify" width="20"></iconify-icon>
    </label>
    <%= link_to "New brand", new_brand_path, class: "btn btn-primary" %>
  </div>

  <div class="overflow-x-auto rounded-box border-2 border-base-content/5 bg-base-100">
    <table class="table table-zebra table-lg" id="brands">
      <thead>
        <tr class="bg-base-300 text-base-content">
          <template x-for="column in columns" :key="column.name">
            <th @click="sort(column.name)" class="cursor-pointer">
              <div class="flex flex-row items-center gap-1">
                <span x-text="column.label"></span>
                <template x-if="sortCol === column.name && !sortAsc">
                  <iconify-icon width="16" icon="mdi:arrow-down" class="text-white">
                  </iconify-icon>
                </template>
                <template x-if="sortCol === column.name && sortAsc">
                  <iconify-icon width="16" icon="mdi:arrow-up" class="text-white">
                  </iconify-icon>
                </template>
              </div>
            </th>
          </template>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <template x-if="isLoading">
          <tr class="hover">
            <td colspan="8" class="text-center">
              <i>Loading...</i>
            </td>
          </tr>
        </template>
        <template x-if="!data.length && !isLoading">
          <tr class="hover">
            <td colspan="8" class="text-center">
              <i>No data found.</i>
            </td>
          </tr>
        </template>
        <template x-for="brand in data" :key="brand._id">
          <tr class="hover">
            <td x-text="brand.name"></td>
            <td>
              <a :href="`/brands/${brand._id}`" class="btn btn-primary">View</a>
            </td>
          </tr>
        </template>
      </tbody>
    </table>
  </div>
</div>

<% content_for :page_script do %>
  <script>
    document.addEventListener("alpine:init", () => {
       Alpine.data('brands', () => ({
        originalData: [],
        data: [],
        sortCol: null,
        sortAsc: null,
        isLoading: true,
        columns: [
          { name: "name", label: "Name" },
        ],
        async init() {
          let resp = await fetch('/brands.json');
          this.originalData = await resp.json();
          this.data = [...this.originalData];
          this.isLoading = false;
        },
        sort (col) {
          this.sortCol = col;
          if (this.sortCol === col && this.sortAsc === false) {
            this.sortCol = null;
            this.sortAsc = null;
            this.data = [...this.originalData];
            return;
          }

          if (this.sortCol === col) this.sortAsc = this.sortAsc === null ? true : !this.sortAsc;
          this.data.sort((a, b) => {
            if (a[this.sortCol] < b[this.sortCol]) return this.sortAsc ? 1 : -1;
            if (a[this.sortCol] > b[this.sortCol]) return this.sortAsc ? -1 : 1;
            return 0;
          });
        },
        search (query) {
          if (!query.trim()) {
            this.data = [...this.originalData];
            return;
          }

          query = query.toLowerCase();
          this.data = [...this.originalData].filter(p => {
            return Object.values(p).some(v => String(v).toLowerCase().includes(query));
          });
        }
      }))
    });
  </script>
<% end %>

app/views/brands/new.html.erb
<% content_for :title, "Create Supplier" %>

<div class="card bg-base-200 shadow-xl">
  <div class="card-body">
    <div class="card-title">
      <h1 class="text-4xl font-bold">Create brand</h1>
    </div>

    <%= render "form", brand: @brand %>
  </div>
</div>

app/views/brands/show.html.erb
<p class="text-green-600"><%= notice %></p>

<div class="card bg-base-200 shadow-xl">
  <div class="card-body">
    <div class="card-title">
      <h1 class="text-4xl font-bold">Brand Details</h1>
    </div>

    <%= render @brand %>

    <div class="card-actions mt-4">
      <%= link_to "Update brand", edit_brand_path(@brand), class: "btn btn-primary" %>
      <%= button_to "Delete brand", @brand, method: :delete, class: "btn btn-error" %>
      <%= link_to "Back", brands_path, class: "btn btn-neutral" %>
    </div>
  </div>
</div>