config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :users
  resources :suppliers
  resources :brands
  resources :products
  resources :purchase_orders
  resources :sales_orders
  resources :inventories

  get "browserconfig", to: "home#browserconfig", constraints: lambda { |req| req.format == :xml }, as: "browserconfig"
  get "site", to: "home#site", constraints: lambda { |req| req.format == :webmanifest }, as: "webmanifest"

  # error pages
  %w(400 403 404 405 406 409 422 500 501).each do |code|
    get code, to: "exceptions#index", defaults: { code: }
  end

  devise_for :users,
    path: "",
    controllers: {
      sessions: "users/sessions",
      passwords: "users/passwords"
    },
    path_names: {
      sign_in: "/login",
      password: "/forgot",
      sign_out: "/logout"
    }
end

app/views/layouts/_content.html.erb
<%= render "layouts/loader" %>
<%= render "layouts/header" %>

<main class="hidden w-full h-full overflow-x-clip" id="main">
  <div class="min-h-[calc(100vh-64px)] w-full">
    <%= yield :outside_container %>

    <div class="container mx-auto overflow-x-auto overflow-y-hidden py-5 flex flex-col gap-2">
      <%= yield %>
    </div>
  </div>
</main>

<%= render "layouts/footer" %>

<%= render partial: "partials/toasts" %>
<%= yield :page_script %>

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png"/>
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png"/>
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png"/>
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png"/>
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="/apple-touch-icon-60x60.png"/>
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png"/>
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png"/>
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png"/>

<link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196"/>
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96"/>
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32"/>
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16"/>
<link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128"/>

<meta name="msapplication-config" content="<%= browserconfig_path(format: :xml) %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/mstile-144x144.png"/>
<meta name="msapplication-square70x70logo" content="/mstile-70x70.png"/>
<meta name="msapplication-square150x150logo" content="/mstile-150x150.png"/>
<meta name="msapplication-wide310x150logo" content="/mstile-310x150.png"/>
<meta name="msapplication-square310x310logo" content="/mstile-310x310.png"/>

<link rel="manifest" href="<%= webmanifest_path(format: :webmanifest) %>">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/favicon.ico">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.erb
<footer class="footer dark:text-[#bfb3a4] text-gray-400 p-4 bg-[#151515] shadow md:flex md:items-center md:justify-between md:p-6 hidden" id="footer">
  <aside class="container flex flex-row gap-2 xs:flex-col">
    <span class="flex-1 text-sm xs:text-center xs:order-3">© 2022-<%= Time.zone.now.year %>
      aldwin7894. All Rights Reserved.</span>
  </aside>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar bg-primary sticky inset-x-0 top-0 z-10 h-[60px] px-4 py-2">
  <div class="navbar-start">
    <%= link_to @project_name.titleize, root_path, class: "btn btn-ghost text-xl text-white", target: "_top" %>
  </div>

  <div class="navbar-center flex">
    <ul class="menu menu-horizontal px-1 text-white">
      <%= render "layouts/header_items" %>
    </ul>
  </div>

  <div class="navbar-end">
    <div class="flex flex-none flex-row items-center gap-2">
      <button class="swap swap-flip" data-toggle-theme="dark,cupcake" data-act-class="swap-active">
        <div class="swap-on">
          <iconify-icon width="32" icon="mdi:white-balance-sunny" class="text-white">
          </iconify-icon>
        </div>
        <div class="swap-off">
          <iconify-icon width="32" icon="mdi:weather-night" class="text-black">
          </iconify-icon>
        </div>
      </button>

      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img alt="avatar" src="https://gravatar.com/avatar/<%= @current_email_hash %>"/>
          </div>
        </div>

        <ul tabindex="-1" class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
          <%= form_with url: destroy_user_session_path, method: :delete do |form| %>
            <li>
              <%= form.submit "Logout" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_header_items.html.erb
<li>
  <details>
    <summary>Maintenance</summary>
    <ul class="p-2">
      <li>
        <%= link_to "Brands", brands_path, target: "_top" %>
      </li>
      <li>
        <%= link_to "Products", products_path, target: "_top" %>
      </li>
      <li>
        <%= link_to "Suppliers", suppliers_path, target: "_top" %>
      </li>
    </ul>
  </details>
</li>
<li>
  <%= link_to "Purchase Orders", purchase_orders_path, target: "_top" %>
</li>
<li>
  <%= link_to "Sales Orders", sales_orders_path, target: "_top" %>
</li>
<li>
  <%= link_to "Inventory", inventories_path, target: "_top" %>
</li>

app/views/layouts/_loader.html.erb
<div class="flex items-center justify-center w-screen h-screen bg-white dark:bg-black" id="loader">
  <%= render partial: "layouts/spinner" %>
</div>

app/views/layouts/_meta.html.erb
<% title ||= @project_name %>

<meta name="application-name" content="<%= title.titleize %>"/>
<meta name="description" content="<%= description %>">
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<meta http-equiv="content-type" content="text/html"/>
<meta charset="UTF-8"/>
<meta name="keywords" content="aldwin7894, <%= title %>">
<meta name="author" content="aldwin7894">

<meta property="og:title" content="<%= title %>">
<meta property="og:description" content="<%= description %>">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= url_for(host: ENV.fetch("RAILS_HOST")) %>">
<meta property="og:image" content="<%= ENV.fetch("RAILS_HOST") %>/favicon-196x196.png">
<meta property="og:site_name" content="<%= title.titleize %>">

<meta property="twitter:card" content="summary">
<meta property="twitter:title" content="<%= title.titleize %>">
<meta property="twitter:description" content="<%= description %>">
<meta property="twitter:image" content="<%= ENV.fetch("RAILS_HOST") %>/favicon-196x196.png">

<link rel="canonical" href="<%= url_for(host: ENV.fetch("RAILS_HOST")) %>">

<%= render "layouts/favicon" %>
<%= render "layouts/preconnect" %>

app/views/layouts/_preconnect.html.erb
<% if !Rails.env.development? %>
<link rel="preconnect" href="<%= ENV.fetch("RAILS_ASSET_HOST") %>" />
<link rel="dns-prefetch" href="<%= ENV.fetch("RAILS_ASSET_HOST") %>" />
<% end %>

app/views/layouts/_spinner.html.erb
<% add_class ||= "w-32 h-32 border-16 text-cyan-600" %>
<div class="relative flex items-center justify-center">
  <div class="absolute border-gray-400 border-solid rounded-full <%= add_class %>">
  </div>
  <div class="absolute border-solid border-current border-l-transparent animate-spin inline-block rounded-full motion-reduce:animate-spin-reduce <%= add_class %>">
    <span class="visually-hidden !absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">Loading...</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% title = content_for(:title) || @project_name.titleize || "Project Airona" %>
    <% description = "Project Description" %>

    <title><%= title %></title>
    <%= render partial: "layouts/meta", locals: { title:, description: } %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag "application", defer: "defer" %>

    <%= yield :head_content %>
  </head>

  <body class="overflow-x-hidden antialiased">
    <%= render "layouts/content" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% title = content_for(:title) || @project_name.titleize || "Project Airona" %>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <meta http-equiv="content-type" content="text/html"/>
    <meta charset="UTF-8"/>

    <%= render "layouts/favicon" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag "application" %>
  </head>

  <body class="overflow-x-hidden antialiased">
    <%= render "layouts/loader" %>

    <main class="hidden w-full h-full overflow-x-clip" id="main">
      <%= yield %>
    </main>

    <%= render partial: "partials/toasts" %>
    <%= yield :page_script %>
  </body>
</html>

app/views/layouts/exception.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% title = content_for(:title) || @project_name.titleize || "Project Airona" %>
    <title>
      <%= "#{title} | Error - #{@status} (#{@response})" %>
    </title>

    <%= render partial: "layouts/meta", locals: { title: "#{title} | Error - #{@status} (#{@response})", description: "Error" } %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag "exception", defer: "defer" %>

    <%= yield :head_content %>
  </head>
  <!-- Body -->
  <body>
    <%= yield %>
  </body>
</html>